---
root: true

plugins:
  - babel

env:
  node: true
  jest: true
  browser: true

parser: "@babel/eslint-parser"
  
parserOptions:
  "requireConfigFile": false
  babelOptions:
    "babelrc": false
    "configFile": false

extends:
  - "airbnb-base"

rules:
  no-console: 0
  no-param-reassign: 0
  import/extensions: 0
